spring:
  application:
    name: spring-ai-ollama-web-search
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3-coder

web:
  search:
    engineUrl: https://html.duckduckgo.com/html/?q=
    timeout: 10000
    maxContentLength: 2000