spring:
#  ai:
#    ollama:
#      base-url: https://ollama.com/api
      chat:
        options:
#          model: gpt-oss:120b
          model: minimax-m2.7:cloud

web:
  search:
    engineUrl: https://ollama.com/api/web_search
    api-key: ${OLLAMA_API_KEY}}