###
GET http://localhost:8080/api/chat?message=Hello, how are you?

###
GET http://localhost:8080/api/web-chat/fetch?message=Summarize this page&url=https://sport.ua

###
GET http://localhost:8080/api/web-chat/search?query=What is result of recent match PSG - Bayern Munich?